out = open(r'f:\AAFIM\src\app\(student)\courses\[slug]\page.tsx', 'a', encoding='utf-8')
def w(s=''):
    out.write(s + '\n')

# Job roles
w("const JOB_ROLES: Record<string, { role: string; salary: string }[]> = {")
w("  'CSE / IT DOMAINS': [")
w("    { role: 'AI Engineer',          salary: '\u20b912.0 LPA+' },")
w("    { role: 'Data Scientist',       salary: '\u20b99.5 LPA+' },")
w("    { role: 'Full Stack Developer', salary: '\u20b98.0 LPA+' },")
w("    { role: 'Cloud Engineer',       salary: '\u20b97.5 LPA+' },")
w("    { role: 'Product Designer',     salary: '\u20b96.5 LPA+' },")
w("  ],")
w("  'MANAGEMENT & COMMERCE': [")
w("    { role: 'Marketing Manager', salary: '\u20b98.0 LPA+' },")
w("    { role: 'Business Analyst',  salary: '\u20b97.0 LPA+' },")
w("    { role: 'HR Manager',        salary: '\u20b96.5 LPA+' },")
w("    { role: 'Finance Analyst',   salary: '\u20b97.5 LPA+' },")
w("    { role: 'Sales Manager',     salary: '\u20b99.0 LPA+' },")
w("  ],")
w("  'ECE DOMAINS': [")
w("    { role: 'Embedded Engineer',  salary: '\u20b97.0 LPA+' },")
w("    { role: 'IoT Developer',      salary: '\u20b96.5 LPA+' },")
w("    { role: 'VLSI Designer',      salary: '\u20b98.5 LPA+' },")
w("    { role: 'Robotics Engineer',  salary: '\u20b97.5 LPA+' },")
w("    { role: 'Signal Processor',   salary: '\u20b96.0 LPA+' },")
w("  ],")
w("  default: [")
w("    { role: 'Industry Specialist', salary: '\u20b96.0 LPA+' },")
w("    { role: 'Project Manager',     salary: '\u20b98.0 LPA+' },")
w("    { role: 'Research Analyst',    salary: '\u20b95.5 LPA+' },")
w("    { role: 'Consultant',          salary: '\u20b97.0 LPA+' },")
w("    { role: 'Team Lead',           salary: '\u20b99.0 LPA+' },")
w("  ],")
w("};")
w()

# Feature cards
w("const FEATURES = [")
w("  { icon: '\U0001f393', title: 'Learn',     desc: 'In-demand skills with industry-relevant curriculum.',  num: '01' },")
w("  { icon: '\u2699\ufe0f',  title: 'Build',     desc: 'Real-world projects to build your portfolio.',         num: '02' },")
w("  { icon: '\U0001f331', title: 'Grow',      desc: 'Expert mentorship and career guidance.',               num: '03' },")
w("  { icon: '\U0001f4bc', title: 'Get Hired', desc: 'Top job opportunities and placement support.',         num: '04' },")
w("  { icon: '\U0001f680', title: 'Achieve',   desc: 'Higher salaries and a successful career.',             num: '05' },")
w("];")
w()

# Journey steps
w("const JOURNEY_STEPS = [")
w("  { num: '01', icon: '\U0001f4a1', title: 'Choose Your Path',  desc: 'Explore domains that excite you' },")
w("  { num: '02', icon: '\U0001f4da', title: 'Learn & Master',    desc: 'Gain in-demand skills step by step' },")
w("  { num: '03', icon: '\u2699\ufe0f',  title: 'Build & Practice', desc: 'Work on projects & real-world use cases' },")
w("  { num: '04', icon: '\U0001f4c8', title: 'Gain Experience',   desc: 'Build your portfolio and stand out' },")
w("  { num: '05', icon: '\U0001f3c6', title: 'Get Placed',        desc: 'Land your dream job and grow further' },")
w("];")
w()

# Why items
w("const WHY_ITEMS = [")
w("  { icon: '\U0001f468\u200d\U0001f3eb', label: 'Industry Expert Mentors' },")
w("  { icon: '\U0001f91d', label: 'Hands-on Learning' },")
w("  { icon: '\U0001f504', label: 'Flexible Learning' },")
w("  { icon: '\U0001f310', label: 'Real-world Projects' },")
w("  { icon: '\U0001f9ed', label: 'Career Guidance' },")
w("  { icon: '\u267e\ufe0f',  label: 'Lifetime Support' },")
w("];")
w()
w("const ease = [0.22, 1, 0.36, 1] as const;")
w()

out.close()
print('Part 3 done')
