# -*- coding: utf-8 -*-
MAIN = ""
MAIN += "\n\n/* === HERO SECTION === */\n"
MAIN += "function HeroSection() {\n"
MAIN += "  return (\n"
MAIN += "    <section\n"
MAIN += "      className=\"relative overflow-hidden\"\n"
MAIN += "      style={{ minHeight: '92vh', background: 'linear-gradient(135deg, #0d0f1e 0%, #1a1a2e 45%, #2d1500 100%)' }}\n"
MAIN += "    >\n"
MAIN += "      {/* Ambient glows */}\n"
MAIN += "      <div className=\"absolute inset-0 pointer-events-none overflow-hidden\">\n"
MAIN += "        <div className=\"absolute -top-20 -left-20 w-[500px] h-[500px] rounded-full opacity-20\"\n"
MAIN += "          style={{ background: 'radial-gradient(circle, #f97316 0%, transparent 70%)' }} />\n"
MAIN += "        <div className=\"absolute -bottom-20 -right-20 w-[600px] h-[600px] rounded-full opacity-10\"\n"
MAIN += "          style={{ background: 'radial-gradient(circle, #ffa800 0%, transparent 70%)' }} />\n"
MAIN += "        <div className=\"absolute inset-0 opacity-[0.04]\"\n"
MAIN += "          style={{ backgroundImage: 'linear-gradient(rgba(249,115,22,0.5) 1px, transparent 1px), linear-gradient(90deg, rgba(249,115,22,0.5) 1px, transparent 1px)', backgroundSize: '60px 60px' }} />\n"
MAIN += "        {[...Array(14)].map((_, i) => (\n"
MAIN += "          <motion.div key={i} className=\"absolute rounded-full\"\n"
MAIN += "            style={{ width: 3 + (i % 4) * 2, height: 3 + (i % 4) * 2, top: `${8 + i * 6}%`, left: `${4 + i * 7}%`, background: i % 3 === 0 ? '#f97316' : i % 3 === 1 ? '#ffa800' : '#ffffff', opacity: 0.25 }}\n"
MAIN += "            animate={{ y: [0, -18, 0], opacity: [0.25, 0.6, 0.25] }}\n"
MAIN += "            transition={{ duration: 3.5 + i * 0.3, repeat: Infinity, ease: 'easeInOut', delay: i * 0.25 }} />\n"
MAIN += "        ))}\n"
MAIN += "      </div>\n"
MAIN += "      <div className=\"relative z-10 max-w-7xl mx-auto px-4 sm:px-6 flex items-center\" style={{ minHeight: '92vh' }}>\n"
MAIN += "        <div className=\"w-full grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-center py-16 lg:py-20\">\n"
MAIN += "          {/* LEFT */}\n"
MAIN += "          <div className=\"flex flex-col gap-6\">\n"
MAIN += "            <motion.div initial={{ opacity: 0, y: -16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, ease: [0.22,1,0.36,1] }}\n"
MAIN += "              className=\"inline-flex items-center gap-2 px-4 py-2 rounded-full w-fit\"\n"
MAIN += "              style={{ background: 'rgba(249,115,22,0.15)', border: '1px solid rgba(249,115,22,0.4)' }}>\n"
MAIN += "              <span className=\"text-orange-400 text-sm\">&#9733;</span>\n"
MAIN += "              <span className=\"text-orange-400 font-bold text-xs sm:text-sm\">Industry Recognized &bull; Globally Accepted</span>\n"
MAIN += "            </motion.div>\n"
MAIN += "            <motion.h1 initial={{ opacity: 0, x: -50 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.8, ease: [0.22,1,0.36,1] }}\n"
MAIN += "              className=\"font-black text-white leading-[1.05]\" style={{ fontSize: 'clamp(2.2rem, 5.5vw, 4rem)' }}>\n"
MAIN += "              Earn Industry-Recognized{' '}\n"
MAIN += "              <span style={{ color: '#f97316', textShadow: '0 0 40px rgba(249,115,22,0.7), 0 0 80px rgba(249,115,22,0.3)' }}>Certifications</span>\n"
MAIN += "            </motion.h1>\n"
MAIN += "            <motion.p initial={{ opacity: 0, x: -30 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.7, delay: 0.15, ease: [0.22,1,0.36,1] }}\n"
MAIN += "              className=\"text-gray-300 text-base sm:text-lg leading-relaxed max-w-xl\">\n"
MAIN += "              Enroll, learn, give exams, and earn globally recognized certificates from Adobe, Microsoft, Cisco, Meta, PMI and 11 more top companies.\n"
MAIN += "            </motion.p>\n"
MAIN += "            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.3, ease: [0.22,1,0.36,1] }}\n"
MAIN += "              className=\"flex flex-col sm:flex-row gap-4\">\n"
MAIN += "              <motion.button whileHover={{ scale: 1.06, boxShadow: '0 0 40px rgba(249,115,22,0.7)' }} whileTap={{ scale: 0.95 }}\n"
MAIN += "                onClick={() => document.getElementById('partners')?.scrollIntoView({ behavior: 'smooth' })}\n"
MAIN += "                className=\"px-8 py-4 rounded-xl font-bold text-white flex items-center justify-center gap-2 text-sm sm:text-base\"\n"
MAIN += "                style={{ background: 'linear-gradient(135deg, #f97316, #ea580c)', boxShadow: '0 0 24px rgba(249,115,22,0.45)' }}>\n"
MAIN += "                Explore Certifications <ArrowRight className=\"w-4 h-4\" />\n"
MAIN += "              </motion.button>\n"
MAIN += "              <motion.button whileHover={{ scale: 1.06, background: 'rgba(249,115,22,0.2)' }} whileTap={{ scale: 0.95 }}\n"
MAIN += "                onClick={() => window.location.href = '/auth'}\n"
MAIN += "                className=\"px-8 py-4 rounded-xl font-bold flex items-center justify-center gap-2 border-2 transition-all text-sm sm:text-base\"\n"
MAIN += "                style={{ borderColor: '#f97316', color: '#f97316', background: 'rgba(249,115,22,0.08)' }}>\n"
MAIN += "                Enroll Now\n"
MAIN += "              </motion.button>\n"
MAIN += "            </motion.div>\n"
MAIN += "            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.45, ease: [0.22,1,0.36,1] }}\n"
MAIN += "              className=\"grid grid-cols-4 gap-4 pt-4 border-t border-white/10\">\n"
MAIN += "              {STATS.map(({ value, label }, i) => (\n"
MAIN += "                <motion.div key={label} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5 + i * 0.08 }} className=\"text-center\">\n"
MAIN += "                  <div className=\"font-black text-white text-xl sm:text-2xl leading-none\" style={{ textShadow: '0 0 16px rgba(249,115,22,0.5)' }}>{value}</div>\n"
MAIN += "                  <div className=\"text-gray-400 text-[10px] sm:text-xs mt-1 uppercase tracking-wider\">{label}</div>\n"
MAIN += "                </motion.div>\n"
MAIN += "              ))}\n"
MAIN += "            </motion.div>\n"
MAIN += "          </div>\n"
MAIN += "          {/* RIGHT - floating certificate card */}\n"
MAIN += "          <motion.div initial={{ opacity: 0, x: 60 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.9, delay: 0.2, ease: [0.22,1,0.36,1] }}\n"
MAIN += "            className=\"relative hidden lg:flex items-center justify-center\">\n"
MAIN += "            <motion.div animate={{ scale: [1, 1.06, 1], opacity: [0.3, 0.6, 0.3] }} transition={{ duration: 3, repeat: Infinity, ease: 'easeInOut' }}\n"
MAIN += "              className=\"absolute inset-0 rounded-3xl pointer-events-none\"\n"
MAIN += "              style={{ background: 'radial-gradient(ellipse, rgba(249,115,22,0.3) 0%, transparent 70%)' }} />\n"
MAIN += "            <motion.div whileHover={{ scale: 1.04, rotateY: 5, rotateX: -3 }} transition={{ duration: 0.4 }}\n"
MAIN += "              className=\"relative w-full max-w-md rounded-3xl overflow-hidden shadow-2xl\"\n"
MAIN += "              style={{ background: 'linear-gradient(135deg, #fffbf5 0%, #fff7ed 50%, #fde8d0 100%)', border: '2px solid rgba(249,115,22,0.5)', boxShadow: '0 0 60px rgba(249,115,22,0.35), 0 30px 80px rgba(0,0,0,0.4)' }}>\n"
MAIN += "              <div className=\"h-2 w-full\" style={{ background: 'linear-gradient(90deg, #f97316, #ffa800, #f97316)' }} />\n"
MAIN += "              <div className=\"p-8\">\n"
MAIN += "                <div className=\"flex items-center justify-between mb-6\">\n"
MAIN += "                  <div>\n"
MAIN += "                    <div className=\"text-xs font-bold text-orange-500 uppercase tracking-widest mb-1\">Adyapan Schools</div>\n"
MAIN += "                    <div className=\"text-xs text-gray-400\">Certificate of Achievement</div>\n"
MAIN += "                  </div>\n"
MAIN += "                  <motion.div animate={{ rotate: [0, 8, -8, 0] }} transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}\n"
MAIN += "                    className=\"w-14 h-14 rounded-full flex items-center justify-center shadow-lg\"\n"
MAIN += "                    style={{ background: 'linear-gradient(135deg, #f97316, #ea580c)', boxShadow: '0 0 24px rgba(249,115,22,0.6)' }}>\n"
MAIN += "                    <Award className=\"w-7 h-7 text-white\" />\n"
MAIN += "                  </motion.div>\n"
MAIN += "                </div>\n"
MAIN += "                <div className=\"h-px bg-gradient-to-r from-transparent via-orange-200 to-transparent mb-6\" />\n"
MAIN += "                <div className=\"text-center mb-6\">\n"
MAIN += "                  <p className=\"text-gray-400 text-xs mb-2\">This certifies that</p>\n"
MAIN += "                  <h3 className=\"font-black text-2xl text-gray-900 mb-1\">Rupesh Kumar Rupak</h3>\n"
MAIN += "                  <p className=\"text-gray-400 text-xs mb-4\">has successfully completed</p>\n"
MAIN += "                  <div className=\"inline-block px-4 py-2 rounded-xl mb-4\"\n"
MAIN += "                    style={{ background: 'linear-gradient(135deg, rgba(249,115,22,0.1), rgba(249,115,22,0.05))', border: '1px solid rgba(249,115,22,0.3)' }}>\n"
MAIN += "                    <span className=\"font-bold text-gray-800 text-sm\">Microsoft Azure Fundamentals</span>\n"
MAIN += "                  </div>\n"
MAIN += "                  <p className=\"text-gray-400 text-xs\">Date Issued: <span className=\"font-semibold text-gray-700\">15-05-2026</span></p>\n"
MAIN += "                </div>\n"
MAIN += "                <div className=\"flex items-center justify-between pt-4 border-t border-orange-100\">\n"
MAIN += "                  <div>\n"
MAIN += "                    <p className=\"font-bold text-gray-800 italic text-sm\">Rupesh Kumar</p>\n"
MAIN += "                    <p className=\"text-xs text-gray-400\">Co-Founder, Adyapan</p>\n"
MAIN += "                  </div>\n"
MAIN += "                  <div className=\"flex items-center gap-2\">\n"
MAIN += "                    <div className=\"grid grid-cols-2 gap-0.5 w-7 h-7\">\n"
MAIN += "                      <div className=\"rounded-sm\" style={{ background: '#F25022' }} />\n"
MAIN += "                      <div className=\"rounded-sm\" style={{ background: '#7FBA00' }} />\n"
MAIN += "                      <div className=\"rounded-sm\" style={{ background: '#00A4EF' }} />\n"
MAIN += "                      <div className=\"rounded-sm\" style={{ background: '#FFB900' }} />\n"
MAIN += "                    </div>\n"
MAIN += "                    <span className=\"font-bold text-gray-700 text-sm\">Microsoft</span>\n"
MAIN += "                  </div>\n"
MAIN += "                </div>\n"
MAIN += "              </div>\n"
MAIN += "              <div className=\"h-1 w-full\" style={{ background: 'linear-gradient(90deg, #f97316, #ffa800, #f97316)' }} />\n"
MAIN += "            </motion.div>\n"
MAIN += "            <motion.div className=\"absolute -top-4 -right-4 w-20 h-20 rounded-2xl flex flex-col items-center justify-center shadow-xl bob\"\n"
MAIN += "              style={{ background: 'linear-gradient(135deg, #1a1a2e, #2d1a00)', border: '2px solid rgba(249,115,22,0.5)' }}>\n"
MAIN += "              <Star className=\"w-6 h-6 text-orange-400 mb-1\" />\n"
MAIN += "              <span className=\"text-white text-[9px] font-bold text-center leading-tight\">GLOBALLY<br/>RECOGNIZED</span>\n"
MAIN += "            </motion.div>\n"
MAIN += "            <motion.div className=\"absolute -bottom-4 -left-4 px-4 py-2 rounded-xl shadow-xl bob-slow flex items-center gap-2\"\n"
MAIN += "              style={{ background: 'linear-gradient(135deg, #10b981, #059669)', boxShadow: '0 0 20px rgba(16,185,129,0.4)' }}>\n"
MAIN += "              <CheckCircle className=\"w-4 h-4 text-white\" />\n"
MAIN += "              <span className=\"text-white text-xs font-bold\">Verified Certificate</span>\n"
MAIN += "            </motion.div>\n"
MAIN += "          </motion.div>\n"
MAIN += "        </div>\n"
MAIN += "      </div>\n"
MAIN += "    </section>\n"
MAIN += "  );\n"
MAIN += "}\n"

with open(r'f:\AAFIM\src\app\(student)\certifications\PageClient.tsx', 'a', encoding='utf-8') as f:
    f.write(MAIN)
print('HeroSection appended OK')
