# -*- coding: utf-8 -*-
SECTIONS = ""

# CERTIFICATE SHOWCASE SECTION
SECTIONS += "\n\n/* === CERTIFICATE SHOWCASE SECTION === */\n"
SECTIONS += "function CertificateShowcase() {\n"
SECTIONS += "  return (\n"
SECTIONS += "    <section className=\"py-20 sm:py-24\" style={{ background: 'linear-gradient(135deg, #1a1a2e 0%, #0d0f1e 100%)' }}>\n"
SECTIONS += "      <div className=\"max-w-7xl mx-auto px-4 sm:px-6\">\n"
SECTIONS += "        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6 }} className=\"text-center mb-14\">\n"
SECTIONS += "          <span className=\"text-xs font-bold text-orange-400 uppercase tracking-widest\">Sample Certificate</span>\n"
SECTIONS += "          <h2 className=\"text-3xl sm:text-4xl md:text-5xl font-extrabold text-white mt-3 mb-4\">\n"
SECTIONS += "            Your Certificate <span style={{ color: '#f97316' }}>Preview</span>\n"
SECTIONS += "          </h2>\n"
SECTIONS += "          <p className=\"text-gray-400 max-w-xl mx-auto text-sm sm:text-base\">This is what your industry-recognized certificate will look like upon successful completion.</p>\n"
SECTIONS += "        </motion.div>\n"
SECTIONS += "        <div className=\"grid grid-cols-1 lg:grid-cols-2 gap-12 items-center\">\n"
SECTIONS += "          {/* Certificate preview */}\n"
SECTIONS += "          <motion.div initial={{ opacity: 0, x: -40 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: 0.7, ease: [0.22,1,0.36,1] }}\n"
SECTIONS += "            className=\"relative\">\n"
SECTIONS += "            <motion.div animate={{ opacity: [0.3, 0.7, 0.3] }} transition={{ duration: 3, repeat: Infinity }}\n"
SECTIONS += "              className=\"absolute -inset-4 rounded-3xl pointer-events-none\"\n"
SECTIONS += "              style={{ background: 'radial-gradient(ellipse, rgba(249,115,22,0.25) 0%, transparent 70%)' }} />\n"
SECTIONS += "            <motion.div whileHover={{ scale: 1.03, y: -6 }} transition={{ duration: 0.35 }}\n"
SECTIONS += "              className=\"relative rounded-3xl overflow-hidden shadow-2xl\"\n"
SECTIONS += "              style={{ background: 'linear-gradient(135deg, #fffbf5 0%, #fff7ed 50%, #fde8d0 100%)', border: '2px solid rgba(249,115,22,0.5)', boxShadow: '0 0 60px rgba(249,115,22,0.3), 0 30px 80px rgba(0,0,0,0.5)' }}>\n"
SECTIONS += "              <div className=\"h-3 w-full\" style={{ background: 'linear-gradient(90deg, #f97316, #ffa800, #f97316)' }} />\n"
SECTIONS += "              <div className=\"p-8 sm:p-10\">\n"
SECTIONS += "                <div className=\"text-center\">\n"
SECTIONS += "                  <div className=\"flex items-center justify-center gap-3 mb-6\">\n"
SECTIONS += "                    <div className=\"w-12 h-12 rounded-full flex items-center justify-center\" style={{ background: 'linear-gradient(135deg, #f97316, #ea580c)' }}>\n"
SECTIONS += "                      <Award className=\"w-6 h-6 text-white\" />\n"
SECTIONS += "                    </div>\n"
SECTIONS += "                    <div className=\"text-left\">\n"
SECTIONS += "                      <div className=\"font-black text-gray-900 text-lg\">ADYAPAN SCHOOLS</div>\n"
SECTIONS += "                      <div className=\"text-xs text-gray-400 uppercase tracking-widest\">SR's Adyapan Edutech Pvt. Ltd.</div>\n"
SECTIONS += "                    </div>\n"
SECTIONS += "                  </div>\n"
SECTIONS += "                  <div className=\"h-px bg-gradient-to-r from-transparent via-orange-300 to-transparent mb-6\" />\n"
SECTIONS += "                  <p className=\"text-gray-400 text-sm mb-2\">This is to certify that</p>\n"
SECTIONS += "                  <h3 className=\"font-black text-3xl text-gray-900 mb-2\" style={{ fontFamily: 'Georgia, serif' }}>Rupesh Kumar Rupak</h3>\n"
SECTIONS += "                  <p className=\"text-gray-400 text-sm mb-4\">has successfully completed the certification program in</p>\n"
SECTIONS += "                  <div className=\"inline-block px-6 py-3 rounded-2xl mb-6\"\n"
SECTIONS += "                    style={{ background: 'linear-gradient(135deg, rgba(249,115,22,0.12), rgba(249,115,22,0.06))', border: '1.5px solid rgba(249,115,22,0.4)' }}>\n"
SECTIONS += "                    <span className=\"font-black text-gray-800 text-lg\">Microsoft Azure Fundamentals</span>\n"
SECTIONS += "                  </div>\n"
SECTIONS += "                  <div className=\"flex items-center justify-center gap-8 mb-6\">\n"
SECTIONS += "                    <div className=\"text-center\">\n"
SECTIONS += "                      <p className=\"text-xs text-gray-400 mb-1\">Date Issued</p>\n"
SECTIONS += "                      <p className=\"font-bold text-gray-800 text-sm\">15-05-2026</p>\n"
SECTIONS += "                    </div>\n"
SECTIONS += "                    <motion.div animate={{ rotate: [0, 5, -5, 0] }} transition={{ duration: 4, repeat: Infinity }}\n"
SECTIONS += "                      className=\"w-16 h-16 rounded-full flex items-center justify-center\"\n"
SECTIONS += "                      style={{ background: 'linear-gradient(135deg, #f97316, #ea580c)', boxShadow: '0 0 20px rgba(249,115,22,0.5)' }}>\n"
SECTIONS += "                      <Star className=\"w-8 h-8 text-white\" />\n"
SECTIONS += "                    </motion.div>\n"
SECTIONS += "                    <div className=\"text-center\">\n"
SECTIONS += "                      <p className=\"text-xs text-gray-400 mb-1\">Certificate ID</p>\n"
SECTIONS += "                      <p className=\"font-bold text-gray-800 text-sm\">ADY-2026-MS-001</p>\n"
SECTIONS += "                    </div>\n"
SECTIONS += "                  </div>\n"
SECTIONS += "                  <div className=\"h-px bg-gradient-to-r from-transparent via-orange-200 to-transparent mb-4\" />\n"
SECTIONS += "                  <div className=\"flex items-center justify-between\">\n"
SECTIONS += "                    <div className=\"text-left\">\n"
SECTIONS += "                      <p className=\"font-bold text-gray-800 italic text-sm\">Rupesh Kumar</p>\n"
SECTIONS += "                      <p className=\"text-xs text-gray-400\">Co-Founder, Adyapan</p>\n"
SECTIONS += "                    </div>\n"
SECTIONS += "                    <div className=\"flex items-center gap-2\">\n"
SECTIONS += "                      <div className=\"grid grid-cols-2 gap-0.5 w-8 h-8\">\n"
SECTIONS += "                        <div className=\"rounded-sm\" style={{ background: '#F25022' }} />\n"
SECTIONS += "                        <div className=\"rounded-sm\" style={{ background: '#7FBA00' }} />\n"
SECTIONS += "                        <div className=\"rounded-sm\" style={{ background: '#00A4EF' }} />\n"
SECTIONS += "                        <div className=\"rounded-sm\" style={{ background: '#FFB900' }} />\n"
SECTIONS += "                      </div>\n"
SECTIONS += "                      <span className=\"font-bold text-gray-700\">Microsoft</span>\n"
SECTIONS += "                    </div>\n"
SECTIONS += "                  </div>\n"
SECTIONS += "                </div>\n"
SECTIONS += "              </div>\n"
SECTIONS += "              <div className=\"h-2 w-full\" style={{ background: 'linear-gradient(90deg, #f97316, #ffa800, #f97316)' }} />\n"
SECTIONS += "            </motion.div>\n"
SECTIONS += "          </motion.div>\n"
SECTIONS += "          {/* Right side info */}\n"
SECTIONS += "          <motion.div initial={{ opacity: 0, x: 40 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: 0.7, delay: 0.15, ease: [0.22,1,0.36,1] }}\n"
SECTIONS += "            className=\"flex flex-col gap-6\">\n"
SECTIONS += "            <div>\n"
SECTIONS += "              <span className=\"inline-block px-3 py-1 rounded-full text-xs font-bold text-orange-400 bg-orange-400/10 border border-orange-400/30 mb-4\">Premium Certificate</span>\n"
SECTIONS += "              <h3 className=\"text-2xl sm:text-3xl font-extrabold text-white mb-4 leading-tight\">A Certificate That Opens Doors Worldwide</h3>\n"
SECTIONS += "              <p className=\"text-gray-400 text-sm sm:text-base leading-relaxed\">Every Adyapan certificate is co-branded with our global partners and carries real weight with employers across 50+ countries.</p>\n"
SECTIONS += "            </div>\n"
SECTIONS += "            {[['Digitally Verified', 'Blockchain-backed verification that cannot be forged.', '#10b981'],\n"
SECTIONS += "              ['Globally Accepted', 'Recognized by 300+ hiring partners worldwide.', '#0ea5e9'],\n"
SECTIONS += "              ['Instant Download', 'Get your certificate as a PDF immediately after passing.', '#f97316'],\n"
SECTIONS += "              ['LinkedIn Ready', 'Add directly to your LinkedIn profile with one click.', '#8b5cf6'],\n"
SECTIONS += "            ].map(([title, desc, color], i) => (\n"
SECTIONS += "              <motion.div key={title} initial={{ opacity: 0, x: 20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}\n"
SECTIONS += "                transition={{ duration: 0.4, delay: i * 0.08 }}\n"
SECTIONS += "                className=\"flex items-start gap-4 p-4 rounded-2xl border border-white/10 bg-white/5\">\n"
SECTIONS += "                <div className=\"w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0\" style={{ background: `${color}22`, border: `1px solid ${color}44` }}>\n"
SECTIONS += "                  <CheckCircle className=\"w-5 h-5\" style={{ color }} />\n"
SECTIONS += "                </div>\n"
SECTIONS += "                <div>\n"
SECTIONS += "                  <h4 className=\"font-bold text-white text-sm mb-1\">{title}</h4>\n"
SECTIONS += "                  <p className=\"text-gray-400 text-xs leading-relaxed\">{desc}</p>\n"
SECTIONS += "                </div>\n"
SECTIONS += "              </motion.div>\n"
SECTIONS += "            ))}\n"
SECTIONS += "            <div className=\"flex gap-3 pt-2\">\n"
SECTIONS += "              <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}\n"
SECTIONS += "                onClick={() => window.location.href = '/auth'}\n"
SECTIONS += "                className=\"flex-1 flex items-center justify-center gap-2 px-6 py-3 rounded-xl font-bold text-white text-sm\"\n"
SECTIONS += "                style={{ background: 'linear-gradient(135deg, #f97316, #ea580c)' }}>\n"
SECTIONS += "                <Download className=\"w-4 h-4\" /> Download Sample\n"
SECTIONS += "              </motion.button>\n"
SECTIONS += "              <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}\n"
SECTIONS += "                className=\"flex-1 flex items-center justify-center gap-2 px-6 py-3 rounded-xl font-bold text-sm border-2 transition-all\"\n"
SECTIONS += "                style={{ borderColor: '#f97316', color: '#f97316', background: 'rgba(249,115,22,0.08)' }}>\n"
SECTIONS += "                <ExternalLink className=\"w-4 h-4\" /> Verify Certificate\n"
SECTIONS += "              </motion.button>\n"
SECTIONS += "            </div>\n"
SECTIONS += "          </motion.div>\n"
SECTIONS += "        </div>\n"
SECTIONS += "      </div>\n"
SECTIONS += "    </section>\n"
SECTIONS += "  );\n"
SECTIONS += "}\n"

with open(r'f:\AAFIM\src\app\(student)\certifications\PageClient.tsx', 'a', encoding='utf-8') as f:
    f.write(SECTIONS)
print('CertificateShowcase appended OK')
