# -*- coding: utf-8 -*-
SECTIONS = ""

# PARTNERS SECTION
SECTIONS += "\n\n/* === PARTNERS SECTION === */\n"
SECTIONS += "function PartnersSection() {\n"
SECTIONS += "  return (\n"
SECTIONS += "    <section id=\"partners\" className=\"py-20 sm:py-24\" style={{ background: 'linear-gradient(180deg, #0d0f1e 0%, #1a1a2e 100%)' }}>\n"
SECTIONS += "      <div className=\"max-w-7xl mx-auto px-4 sm:px-6\">\n"
SECTIONS += "        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6, ease: [0.22,1,0.36,1] }} className=\"text-center mb-14\">\n"
SECTIONS += "          <span className=\"text-xs font-bold text-orange-400 uppercase tracking-widest\">16+ Global Partners</span>\n"
SECTIONS += "          <h2 className=\"text-3xl sm:text-4xl md:text-5xl font-extrabold text-white mt-3 mb-4\">\n"
SECTIONS += "            Global <span style={{ color: '#f97316' }}>Certification Partners</span>\n"
SECTIONS += "          </h2>\n"
SECTIONS += "          <p className=\"text-gray-400 max-w-xl mx-auto text-sm sm:text-base\">Earn certificates from the world's most recognized technology companies. Validate your skills and stand out to employers.</p>\n"
SECTIONS += "        </motion.div>\n"
SECTIONS += "        <div className=\"grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-4 gap-4 sm:gap-5\">\n"
SECTIONS += "          {PARTNERS.map((partner, i) => (\n"
SECTIONS += "            <PartnerCard key={partner.name} partner={partner} i={i} />\n"
SECTIONS += "          ))}\n"
SECTIONS += "        </div>\n"
SECTIONS += "        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5, delay: 0.2 }} className=\"text-center mt-12\">\n"
SECTIONS += "          <motion.button whileHover={{ scale: 1.06, boxShadow: '0 0 32px rgba(249,115,22,0.5)' }} whileTap={{ scale: 0.95 }}\n"
SECTIONS += "            onClick={() => window.location.href = '/auth'}\n"
SECTIONS += "            className=\"inline-flex items-center gap-2 px-8 py-4 rounded-xl font-bold text-white shadow-lg\"\n"
SECTIONS += "            style={{ background: 'linear-gradient(135deg, #f97316, #ea580c)', boxShadow: '0 0 16px rgba(249,115,22,0.3)' }}>\n"
SECTIONS += "            Get Certified Now <ArrowRight className=\"w-4 h-4\" />\n"
SECTIONS += "          </motion.button>\n"
SECTIONS += "        </motion.div>\n"
SECTIONS += "      </div>\n"
SECTIONS += "    </section>\n"
SECTIONS += "  );\n"
SECTIONS += "}\n"

# CATEGORIES SECTION
SECTIONS += "\n\n/* === CATEGORIES SECTION === */\n"
SECTIONS += "function CategoriesSection() {\n"
SECTIONS += "  return (\n"
SECTIONS += "    <section className=\"py-20 sm:py-24 bg-white\">\n"
SECTIONS += "      <div className=\"max-w-7xl mx-auto px-4 sm:px-6\">\n"
SECTIONS += "        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6 }} className=\"text-center mb-14\">\n"
SECTIONS += "          <span className=\"text-xs font-bold text-orange-500 uppercase tracking-widest\">Browse by Domain</span>\n"
SECTIONS += "          <h2 className=\"text-3xl sm:text-4xl md:text-5xl font-extrabold text-gray-900 mt-3 mb-4\">\n"
SECTIONS += "            Certification <span style={{ color: '#f97316' }}>Categories</span>\n"
SECTIONS += "          </h2>\n"
SECTIONS += "          <p className=\"text-gray-500 max-w-xl mx-auto text-sm sm:text-base\">Choose from 10 high-demand domains and earn certifications that employers actively seek.</p>\n"
SECTIONS += "        </motion.div>\n"
SECTIONS += "        <div className=\"grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 sm:gap-5\">\n"
SECTIONS += "          {CATEGORIES.map((cat, i) => (\n"
SECTIONS += "            <motion.div key={cat.name}\n"
SECTIONS += "              initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}\n"
SECTIONS += "              transition={{ duration: 0.5, delay: i * 0.06, ease: [0.22,1,0.36,1] }}\n"
SECTIONS += "              whileHover={{ y: -8, boxShadow: `0 20px 40px ${cat.color}22` }}\n"
SECTIONS += "              className=\"group bg-white rounded-2xl p-5 text-center cursor-pointer border border-gray-100 shadow-sm hover:border-orange-200 transition-all duration-300\"\n"
SECTIONS += "            >\n"
SECTIONS += "              <motion.div whileHover={{ scale: 1.2, rotate: [0, -8, 8, 0] }} transition={{ duration: 0.4 }}\n"
SECTIONS += "                className=\"text-3xl mb-3 block\">{cat.icon}</motion.div>\n"
SECTIONS += "              <h3 className=\"font-bold text-gray-900 text-sm mb-1 leading-tight\">{cat.name}</h3>\n"
SECTIONS += "              <p className=\"text-xs font-semibold\" style={{ color: cat.color }}>{cat.count}</p>\n"
SECTIONS += "              <div className=\"mt-3 h-0.5 w-0 group-hover:w-full mx-auto rounded-full transition-all duration-500\"\n"
SECTIONS += "                style={{ background: `linear-gradient(90deg, ${cat.color}, ${cat.color}66)` }} />\n"
SECTIONS += "            </motion.div>\n"
SECTIONS += "          ))}\n"
SECTIONS += "        </div>\n"
SECTIONS += "      </div>\n"
SECTIONS += "    </section>\n"
SECTIONS += "  );\n"
SECTIONS += "}\n"

# HOW IT WORKS SECTION
SECTIONS += "\n\n/* === HOW IT WORKS SECTION === */\n"
SECTIONS += "function HowItWorksSection() {\n"
SECTIONS += "  return (\n"
SECTIONS += "    <section className=\"py-20 sm:py-24\" style={{ background: 'linear-gradient(135deg, #fff7ed 0%, #fef3c7 50%, #fff 100%)' }}>\n"
SECTIONS += "      <div className=\"max-w-7xl mx-auto px-4 sm:px-6\">\n"
SECTIONS += "        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6 }} className=\"text-center mb-16\">\n"
SECTIONS += "          <span className=\"text-xs font-bold text-orange-500 uppercase tracking-widest\">Simple Process</span>\n"
SECTIONS += "          <h2 className=\"text-3xl sm:text-4xl md:text-5xl font-extrabold text-gray-900 mt-3 mb-4\">\n"
SECTIONS += "            How It <span style={{ color: '#f97316' }}>Works</span>\n"
SECTIONS += "          </h2>\n"
SECTIONS += "          <p className=\"text-gray-500 max-w-2xl mx-auto text-sm sm:text-base\">Your journey from enrollment to a globally recognized certificate in 6 clear steps.</p>\n"
SECTIONS += "        </motion.div>\n"
SECTIONS += "        <div className=\"relative\">\n"
SECTIONS += "          {/* Connecting line desktop */}\n"
SECTIONS += "          <div className=\"hidden lg:block absolute top-[52px] left-[8%] right-[8%] h-0.5\"\n"
SECTIONS += "            style={{ background: 'linear-gradient(90deg, #f97316, #fbbf24, #ec4899, #f97316)' }} />\n"
SECTIONS += "          <div className=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-6 sm:gap-8\">\n"
SECTIONS += "            {STEPS.map((step, i) => {\n"
SECTIONS += "              const Icon = step.icon;\n"
SECTIONS += "              return (\n"
SECTIONS += "                <motion.div key={step.num}\n"
SECTIONS += "                  initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}\n"
SECTIONS += "                  transition={{ duration: 0.5, delay: i * 0.1, ease: [0.22,1,0.36,1] }}\n"
SECTIONS += "                  whileHover={{ y: -8 }}\n"
SECTIONS += "                  className=\"flex flex-col items-center text-center group\"\n"
SECTIONS += "                >\n"
SECTIONS += "                  <span className=\"text-xs font-black mb-2\" style={{ color: step.color }}>{step.num}</span>\n"
SECTIONS += "                  <motion.div\n"
SECTIONS += "                    whileHover={{ scale: 1.15, boxShadow: `0 0 28px ${step.color}66` }}\n"
SECTIONS += "                    transition={{ duration: 0.25 }}\n"
SECTIONS += "                    className=\"w-20 h-20 rounded-full flex items-center justify-center mb-4 shadow-lg relative z-10\"\n"
SECTIONS += "                    style={{ background: '#1a1a2e', border: `2px solid ${step.color}44` }}\n"
SECTIONS += "                  >\n"
SECTIONS += "                    <Icon className=\"w-8 h-8\" style={{ color: step.color }} />\n"
SECTIONS += "                  </motion.div>\n"
SECTIONS += "                  <h3 className=\"font-bold text-gray-900 text-base mb-2\">{step.title}</h3>\n"
SECTIONS += "                  <p className=\"text-gray-500 text-xs sm:text-sm leading-relaxed\">{step.desc}</p>\n"
SECTIONS += "                </motion.div>\n"
SECTIONS += "              );\n"
SECTIONS += "            })}\n"
SECTIONS += "          </div>\n"
SECTIONS += "        </div>\n"
SECTIONS += "      </div>\n"
SECTIONS += "    </section>\n"
SECTIONS += "  );\n"
SECTIONS += "}\n"

with open(r'f:\AAFIM\src\app\(student)\certifications\PageClient.tsx', 'a', encoding='utf-8') as f:
    f.write(SECTIONS)
print('Partners + Categories + HowItWorks appended OK')
